linter:
  rules:
    - avoid_print
    - unnecessary_new
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_single_quotes
    - always_specify_types
    - annotate_overrides
    - public_member_api_docs
    - lines_longer_than_80_chars
    - type_annotate_public_apis
    - avoid_types_on_closure_parameters
    - prefer_is_empty
    - prefer_contains
    - use_key_in_widget_constructors